#!/usr/bin/env python3
"""Mirror docs/*.md of Cris7015/xr500v-openwrt into the repository's GitHub Wiki.

The wiki is flat and links pages without the .md extension, so page-to-page links are
rewritten, links that leave docs/ become absolute GitHub URLs, every page gets a one-line
"generated mirror" banner and _Sidebar.md is regenerated.  Nothing is edited by hand in
the wiki: docs/ is the source of truth.

usage: sync-github-wiki.py <repo-checkout> [--push]"""
import datetime
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

REPO = 'https://github.com/Cris7015/xr500v-openwrt'
WIKI = REPO + '.wiki.git'
TITLES = {  # sidebar labels
    '02': 'Hardware & Chips', '03': 'Boot, Partitions & Flashing', '04': 'Ethernet & DSA',
    '05': 'Wi-Fi (MT7603 / MT7662)', '06': 'VoIP / FXS Telephony', '07': 'USB, RAM & Peripherals',
    '08': 'Front-Panel LEDs', '09': 'GPON / xPON Status', '10': 'Stock Firmware Access',
    '11': 'Build & Persistence', '12': 'U-Boot + UBI migration',
}


def rewrite(target, page):
    if not target or target.startswith(('http://', 'https://', 'mailto:', '#')):
        return target
    path, _, anchor = target.partition('#')
    anchor = ('#' + anchor) if anchor else ''
    if re.fullmatch(r'(Home|\d\d-[a-z0-9-]+)\.md', path):
        return path[:-3] + anchor
    if path.startswith('../'):
        rel = path[3:]
        kind = 'tree' if rel.endswith('/') else 'blob'
        return f'{REPO}/{kind}/main/{rel}{anchor}'
    kind = 'tree' if path.endswith('/') else 'blob'
    return f'{REPO}/{kind}/main/docs/{path}{anchor}'


def convert(text, page, today):
    banner = (f'> _Mirror of [`docs/`]({REPO}/tree/main/docs) in the repository, generated {today} by '
              f'`scripts/sync-github-wiki.py`. Edit the files in `docs/`, not the wiki._\n\n')
    body = re.sub(r'\]\(([^)\s]*)\)', lambda m: '](' + rewrite(m.group(1), page) + ')', text)
    return banner + body


def sidebar(pages):
    lines = ['### 📡 TP-Link Archer XR500v', '', '**[🏠 Home](Home)**', '', '**Teardown & OpenWrt port**', '']
    for p in pages:
        num = p.stem[:2]
        if num in TITLES:
            lines.append(f'- [{num} · {TITLES[num]}]({p.stem})')
    lines += ['', '---', '', f'[← Source repo]({REPO}) · [Releases]({REPO}/releases)', '']
    return '\n'.join(lines)


def main():
    repo = pathlib.Path(sys.argv[1]).resolve()
    push = '--push' in sys.argv
    docs = repo / 'docs'
    pages = sorted(p for p in docs.glob('*.md') if p.stem == 'Home' or re.fullmatch(r'\d\d-[a-z0-9-]+', p.stem))
    assert {p.stem[:2] for p in pages} >= set(TITLES), 'missing chapters'
    today = datetime.date.today().isoformat()
    work = pathlib.Path(tempfile.mkdtemp(prefix='xr500v-wiki-'))
    subprocess.run(['git', 'clone', '-q', WIKI, str(work)], check=True)
    for old in work.glob('*.md'):
        old.unlink()
    for p in pages:
        (work / p.name).write_text(convert(p.read_text(), p.stem, today))
    (work / '_Sidebar.md').write_text(sidebar(pages))
    leftovers = [(f.name, m) for f in work.glob('*.md') for m in re.findall(r'\]\((\d\d-[a-z0-9-]+\.md[^)]*|Home\.md[^)]*|\.\./[^)]*)\)', f.read_text())]
    assert not leftovers, leftovers
    status = subprocess.run(['git', 'status', '--short'], cwd=work, capture_output=True, text=True, check=True).stdout
    print(status or '(wiki already up to date)')
    if not status or not push:
        print('dry run, nothing pushed' if not push else 'nothing to push'); print(work); return
    msg = (f'Mirror docs/ as of {today}\n\nGenerated by scripts/sync-github-wiki.py from the repository docs/ directory: status refreshed to '
           f'the September 2026 state, chapter 12 (U-Boot + UBI migration) added, sidebar regenerated.\n\n'
           'Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>\n')
    subprocess.run(['git', '-c', 'user.name=Cris', '-c', 'user.email=pcristian292@gmail.com', '-c', 'commit.gpgsign=false', 'add', '-A'], cwd=work, check=True)
    subprocess.run(['git', '-c', 'user.name=Cris', '-c', 'user.email=pcristian292@gmail.com', '-c', 'commit.gpgsign=false', 'commit', '-q', '-m', msg], cwd=work, check=True)
    subprocess.run(['git', 'push', '-q', 'origin', 'HEAD:master'], cwd=work, check=True)
    head = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], cwd=work, capture_output=True, text=True, check=True).stdout.strip()
    print(f'pushed {head} ({len(pages)} pages + _Sidebar.md)')
    shutil.rmtree(work, ignore_errors=True)


if __name__ == '__main__':
    main()
